apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: wordpress
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
    scrape_configs:
      - job_name: 'prometheus'
        static_configs:
          - targets: ['localhost:9090']

      - job_name: 'wordpress.raja-ch.me'
        scheme: https
        tls_config:
        static_configs:
          - targets: ['wordpress.raja-ch.me:443']
