apiVersion: v1
kind: ConfigMap
metadata:
  name: blackbox-exporter-config
  namespace: wordpress
data:
  config.yml: |
    modules:
      http_2xx_example:
        prober: http
        timeout: 5s
        http:
          valid_http_versions: [HTTP/1.1, HTTP/2]
          valid_status_codes: []  # Include i codici di stato HTTP validi che desideri monitorare
          method: GET
          valid_http_versions: [HTTP/1.1, HTTP/2]
          fail_if_ssl: false  # Imposta su true se desideri che la verifica SSL sia obbligatoria
          fail_if_not_ssl: false  # Imposta su true se desideri che la verifica SSL non sia consentita
