apiVersion: apps/v1
kind: Deployment
metadata:
  name: blackbox-exporter
  namespace: wordpress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blackbox-exporter
  template:
    metadata:
      labels:
        app: blackbox-exporter
    spec:
      containers:
        - name: blackbox-exporter
          image: prom/blackbox-exporter:latest  # 
          ports:
            - containerPort: 9115  # 
          args:
            - '--config.file=/etc/blackbox-exporter/config.yml'
          volumeMounts:
            - name: config-volume
              mountPath: /etc/blackbox-exporter
              readOnly: true
      volumes:
        - name: config-volume
          configMap:
            name: blackbox-exporter-config 

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: blackbox-exporter-config
  namespace: wordpress
data:
  config.yml: |
    modules:
      http_2xx_example:
        prober: http
        timeout: 5s
        http:
          valid_http_versions: [HTTP/1.1, HTTP/2]
          valid_status_codes: []  # Include i codici di stato HTTP validi che desideri monitorare
          method: GET
          valid_http_versions: [HTTP/1.1, HTTP/2]
          fail_if_ssl: false  # Imposta su true se desideri che la verifica SSL sia obbligatoria
          fail_if_not_ssl: false  # Imposta su true se desideri che la verifica SSL non sia consentita
