apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus
  namespace: wordpress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      containers:
        - name: prometheus
          image: bitnami/prometheus
          ports:
            - containerPort: 9090