apiVersion: v1
kind: Service
metadata:
  name: prometheus
  namespace: wordpress
spec:
  selector:
    app: prometheus
  ports:
  - protocol: TCP
    port: 90
    targetPort: 9090
  type: LoadBalancer
