apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: auth
  namespace: wordpress
spec:
  basicAuth:
    removeHeader: false
    secret: authsecret

---
apiVersion: v1
kind: Secret
metadata:
  name: authsecret
  namespace: wordpress 
data:
  users: 
    dXNlcjokYXByMSQwdERsbjBKZyR4LnlyUk8ubVltdm1mNmxUNG9rNWExCgo=
