apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: auth
  namespace: wordpress
spec:
  basicAuth:
    removeHeader: false
    secret: authsecret

---

apiVersion: v1
kind: Secret
metadata:
  name: authsecret
  namespace: wordpress 
data: 
  username: cmFqYQ==
  password: cmpjaDg=


