apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: wordpress
  labels:
    app: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: demo-mysql-container 
          image: mysql:8
          imagePullPolicy: IfNotPresent      
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: mysql-init
              mountPath: /docker-entrypoint-initdb.d
            - name: mysql-data
              mountPath: /var/lib/mysql
          env:
            - name: MYSQL_DATABASE
              value: wordpress
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: wp-secrets
                  key: MYSQL_ROOT_PASSWORD                 
      volumes:
        - name: mysql-init
          configMap:
            name: mysql-wp-config
        - name: mysql-data    
          persistentVolumeClaim:
            claimName: mysql-pvc
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-wp-config
  namespace: wordpress
data:
  init.sql: |
    CREATE DATABASE IF NOT EXISTS wordpress;
